Add options -p and -S.
Add -p (set shell prompt PS1) to identify the host in each pane (set it to the
command line host name). This is a simple hack. We'd rather set pane_title in
tmux, but that seems to be cumbersome.

Add -S (execute "tmux set-window-option synchronize-panes on").

diff --git a/hostmux b/hostmux
--- a/hostmux
+++ b/hostmux
@@ -1,39 +1,40 @@
 #!/bin/sh
 
 # Keybinding suggestions for .tmux.conf:
-# bind-key a set-window-option synchronize-panes
-# bind-key X kill-session
+#   bind-key a set-window-option synchronize-panes (see also -S)
+#   bind-key X kill-session
 
-
-USAGE="hostmux [-h] [-x] [-l <tmux layout>] [-s <session name>] HOST A [, HOST B, HOST N]"
+USAGE="hostmux [-hxpS] [-l <tmux layout>] [-s <session name>] HOST_A [, HOST_B, HOST_N]"
 
 # Default Settings
 SESSION_NAME=hostmux
 LAYOUT=even-vertical
 CLOSE=
+SETPROMPT=false
+SYNCPANES=false
 
 # Get optional user settings
-while getopts s:l:hx opt
-do
-case $opt in
-s)     SESSION_NAME=$OPTARG
-       ;;
-l)     LAYOUT=$OPTARG
-       ;;
-x)     CLOSE=" && exit"
-       ;;
-h)     echo $USAGE
-       exit 1
-       ;;
-'?')   echo "$0: invalid option -$OPTARG" >&2
-       echo $USAGE >&2
-       exit 1
-       ;;
+while getopts s:l:hxpS opt; do
+    case $opt in
+    s)     SESSION_NAME=$OPTARG
+           ;;
+    l)     LAYOUT=$OPTARG
+           ;;
+    x)     CLOSE=" && exit"
+           ;;
+    p)     SETPROMPT=true
+           ;;   
+    S)     SYNCPANES=true
+           ;;   
+    h)     echo $USAGE
+           exit 0
+           ;;
+    '?')   echo "$0: invalid option -$OPTARG" >&2
+           echo $USAGE >&2
+           exit 1
+           ;;
 esac done
 shift $((OPTIND - 1))
-
-echo $#
-echo $LAYOUT
 
 # The actual script
 NUMBER_OF_HOSTS=$#
@@ -45,13 +46,12 @@ tmux -2 new-session -d -s $SESSION_NAME
 # the layout each time for even distribution
 LOOP_INDEX=1
 
-while [ $LOOP_INDEX -lt $NUMBER_OF_HOSTS ]
-do
-  tmux split-window -h -d
-  tmux select-layout $LAYOUT
-
-  LOOP_INDEX=$(($LOOP_INDEX+1))
+while [ $LOOP_INDEX -lt $NUMBER_OF_HOSTS ]; do
+    tmux split-window -h -d
+    tmux select-layout $LAYOUT
+    LOOP_INDEX=$(($LOOP_INDEX+1))
 done
+
 
 # Check what pane-base-index is configured and use it for addressing
 # the panes
@@ -62,14 +62,18 @@ PANE_MAX=$(($PANE_INDEX+$NUMBER_OF_HOSTS-1))
 # then shift the argument list left, increase the index and go
 # into next iteration. Now $1 refers to the next argument passed
 # to the script
-while [ $PANE_INDEX -le $PANE_MAX ]
-do
-  tmux send-keys -t $PANE_INDEX "ssh $1 $CLOSE" C-m
-
-  shift
-  PANE_INDEX=$(($PANE_INDEX+1))
+while [ $PANE_INDEX -le $PANE_MAX ]; do
+    tmux send-keys -t $PANE_INDEX "ssh $1 $CLOSE" C-m
+    if $SETPROMPT; then
+        tmux send-keys -t $PANE_INDEX "export PS1='[\\u@$1 \\w]$ '" C-m
+    fi
+    shift
+    PANE_INDEX=$(($PANE_INDEX+1))
 done
 
+if $SYNCPANES; then
+    tmux set-window-option synchronize-panes on
+fi
 
 # Attach to the session
 tmux -2 attach-session -t $SESSION_NAME
