Add -a, -p, -P
-a: set synchronize-panes: sync commands in all panes
-p: set pane_title: identify each pane by name
-P: set PS1: identify each pane by remote shell prompt

pane_title
----------
When using -p, then hostmux will try to display the command line hostname
(host1, host2, ...) in the border of every pane. This is done by setting the
tmux variable pane_title [man_tmux] via printf '\033]2;hostN\007. This works,
unless the remote machine does some PS1 magic which involves setting the
terminal title [term_title] (e.g. in bash: PS1="\[\033]0;\u@\h:\w\007\]$ ").
Then, tmux uses that title as pane_title and, for unknown reasons, resetting
it using printf doesn't change pane_title anymore. In that case, you can
either simplify the remote's PS1 magic (e.g. just PS1="[\u@\h:\w]$ ") or
force PS1="[hostN]$ " using hostmux -P (capital P).
We also unset PROMPT_COMMAND, which can mess up pane_title even if PS1 is ok.

Even more technical note:

Slight change in the printf escapes: We end the sequence with BEL (\007) (see
several xterm manuals)
    printf '\033]2;hostN\007'
instead of
    printf '\033]2;hostN\033\\'
as stated in the tmux man page. Both work (tested: remote=bash+Linux,
zsh+Linux, zsh+FreeBSD).

remote history
--------------
We prefix all remote commands with a whitespace (see also [history_commit]),
which prevents the command from showing up in the remote machine's history. But
note that this needs shell-specific settings in order to have an effect. See
http://unix.stackexchange.com/q/6094 . For instance

zsh: setopt HIST_IGNORE_SPACE
bash: HISTCONTROL=ignorespace

Refs:
    [man_tmux]: https://www.freebsd.org/cgi/man.cgi?query=tmux&sektion=1&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports#NAMES_AND_TITLES
    [term_title]: http://tldp.org/HOWTO/Xterm-Title-3.html
    [history_commit] https://github.com/hukl/hostmux/commit/63c37d62a0310e0f345512102b3f483207a148ba

diff --git a/hostmux b/hostmux
--- a/hostmux
+++ b/hostmux
@@ -1,41 +1,39 @@
 #!/bin/sh
 
-# Keybinding suggestions for .tmux.conf:
-# bind-key a set-window-option synchronize-panes
-# bind-key X kill-session
+USAGE="hostmux -h | [-xpPa] [-l <tmux layout>] [-s <session name>] host1 [host2 ...]"
 
-
-USAGE="hostmux [-h] [-x] [-l <tmux layout>] [-s <session name>] HOST A [, HOST B, HOST N]"
-
-# Default Settings
 SESSION_NAME=hostmux
 LAYOUT=even-vertical
 CLOSE=
+SET_PANE_TITLE=false
+SET_PROMPT=false
+SYNC_PANES=false
 
 # Get optional user settings
-while getopts s:l:hx opt
-do
-case $opt in
-s)     SESSION_NAME=$OPTARG
-       ;;
-l)     LAYOUT=$OPTARG
-       ;;
-x)     CLOSE=" && exit"
-       ;;
-h)     echo $USAGE
-       exit 1
-       ;;
-'?')   echo "$0: invalid option -$OPTARG" >&2
-       echo $USAGE >&2
-       exit 1
-       ;;
+while getopts s:l:hxpPa opt; do
+    case $opt in
+    s)     SESSION_NAME=$OPTARG
+           ;;
+    l)     LAYOUT=$OPTARG
+           ;;
+    x)     CLOSE=" && exit"
+           ;;
+    p)     SET_PANE_TITLE=true
+           ;;   
+    P)     SET_PROMPT=true
+           ;;   
+    a)     SYNC_PANES=true
+           ;;   
+    h)     echo $USAGE
+           exit 0
+           ;;
+    '?')   echo "$0: invalid option -$OPTARG" >&2
+           echo $USAGE >&2
+           exit 1
+           ;;
 esac done
 shift $((OPTIND - 1))
 
-echo $#
-echo $LAYOUT
-
-# The actual script
 NUMBER_OF_HOSTS=$#
 
 # Initialize Session
@@ -45,12 +43,10 @@ tmux -2 new-session -d -s $SESSION_NAME
 # the layout each time for even distribution
 LOOP_INDEX=1
 
-while [ $LOOP_INDEX -lt $NUMBER_OF_HOSTS ]
-do
-  tmux split-window -h -d
-  tmux select-layout $LAYOUT
-
-  LOOP_INDEX=$(($LOOP_INDEX+1))
+while [ $LOOP_INDEX -lt $NUMBER_OF_HOSTS ]; do
+    tmux split-window -h -d
+    tmux select-layout $LAYOUT
+    LOOP_INDEX=$(($LOOP_INDEX+1))
 done
 
 # Check what pane-base-index is configured and use it for addressing
@@ -58,18 +54,32 @@ done
 PANE_INDEX=$(tmux show-window-options -g -v pane-base-index)
 PANE_MAX=$(($PANE_INDEX+$NUMBER_OF_HOSTS-1))
 
+
+# http://stackoverflow.com/questions/9747952/pane-title-in-tmux
+if $SET_PANE_TITLE; then
+    tmux set-window-option -g pane-border-status top
+    tmux set-window-option -g pane-border-format " #{pane_index} [#{pane_title}] "
+fi
+
 # Loop through the panes and take the first argument as a ssh host
 # then shift the argument list left, increase the index and go
 # into next iteration. Now $1 refers to the next argument passed
 # to the script
-while [ $PANE_INDEX -le $PANE_MAX ]
-do
-  tmux send-keys -t $PANE_INDEX " ssh $1 $CLOSE" C-m
-
-  shift
-  PANE_INDEX=$(($PANE_INDEX+1))
+while [ $PANE_INDEX -le $PANE_MAX ]; do
+    tmux send-keys -t $PANE_INDEX " ssh $1 $CLOSE" C-m
+    if $SET_PROMPT; then
+        tmux send-keys -t $PANE_INDEX " export PS1=\"[$1]$ \"" C-m
+    fi
+    if $SET_PANE_TITLE; then
+        tmux send-keys -t $PANE_INDEX " unset PROMPT_COMMAND; printf '\033]2;$1\007'" C-m
+    fi
+    shift
+    PANE_INDEX=$(($PANE_INDEX+1))
 done
 
+if $SYNC_PANES; then
+    tmux set-window-option synchronize-panes on
+fi
 
 # Attach to the session
 tmux -2 attach-session -t $SESSION_NAME
